stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/processed

  augment:
    cmd: python src/augment.py
    deps:
      - data/processed
      - src/augment.py
    params:
      - augment
    outs:
      - data/augmented

  train:
    cmd: python src/train.py
    deps:
      - data/augmented
      - src/train.py
    params:
      - train
    outs:
      - models/model.pt

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/processed
      - models/model.pt
      - src/evaluate.py
    params:
      - train
    metrics:
      - metrics.json:
          cache: false